site_name: MyCalc Documentation
nav:
  - Home: index.md
  - CLI Apps: cli.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
theme:
  name: material
