name: mkdocs-build-deployment

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "2.1.1"
          cache-venv: "true"
          cache-poetry: "true"

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build docs
        run: poetry run mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
